[
    [
        "1037",
        "1043",
        "translatedPath",
        "ActivateWindow(Programs,Addons,return)"
    ],
    [
        "1037",
        "1043",
        "icon",
        "DefaultAddonProgram.png"
    ],
    [
        "1037",
        "1038",
        "translatedPath",
        "ActivateWindow(MusicLibrary,Addons,return)"
    ],
    [
        "1037",
        "1038",
        "icon",
        "DefaultAddonMusic.png"
    ],
    [
        "1037",
        "1039",
        "translatedPath",
        "ActivateWindow(Pictures,Addons,return)"
    ],
    [
        "1037",
        "1039",
        "icon",
        "DefaultAddonPicture.png"
    ],
    [
        "mainmenu",
        "b-movies-b",
        "widget",
        "Addon"
    ],
    [
        "mainmenu",
        "b-movies-b",
        "widgetName",
        "XPrime - Trending"
    ],
    [
        "mainmenu",
        "b-movies-b",
        "widgetType",
        "movies"
    ],
    [
        "mainmenu",
        "b-movies-b",
        "widgetTarget",
        "videos"
    ],
    [
        "mainmenu",
        "b-movies-b",
        "widgetPath",
        "plugin://plugin.video.xprime/?action=movies&url=trakt_trending&reload=$INFO[Window(Home).Property(widgetreload-movies)]"
    ],
    [
        "mainmenu",
        "b-movies-b",
        "widget.2",
        "Addon"
    ],
    [
        "mainmenu",
        "b-movies-b",
        "widgetName.2",
        "StreamLord - [B]Hot Movies[/B]"
    ],
    [
        "mainmenu",
        "b-movies-b",
        "widgetType.2",
        "videos"
    ],
    [
        "mainmenu",
        "b-movies-b",
        "widgetTarget.2",
        "videos"
    ],
    [
        "mainmenu",
        "b-movies-b",
        "widgetPath.2",
        "plugin://plugin.video.streamlord/?action=movies&reload=$INFO[Window(Home).Property(widgetreload-movies)]"
    ],
    [
        "mainmenu",
        "b-movies-b",
        "widgetStyle",
        "Panel"
    ],
    [
        "mainmenu",
        "b-movies-b",
        "widgetCase",
        "Glass"
    ],
    [
        "mainmenu",
        "b-movies-b",
        "widgetLimit",
        "$NUMBER[100]"
    ],
    [
        "mainmenu",
        "b-movies-b",
        "widgetStyle.2",
        "Panel"
    ],
    [
        "mainmenu",
        "b-movies-b",
        "widgetLimit.2",
        "$NUMBER[100]"
    ],
    [
        "mainmenu",
        "b-movies-b",
        "icon",
        "DefaultShortcut.png"
    ],
    [
        "mainmenu",
        "b-movies-b",
        "thumb",
        "thumb"
    ],
    [
        "mainmenu",
        "b-tvseries-b",
        "widget",
        "Addon"
    ],
    [
        "mainmenu",
        "b-tvseries-b",
        "widgetName",
        "XPrime - Trending"
    ],
    [
        "mainmenu",
        "b-tvseries-b",
        "widgetType",
        "videos"
    ],
    [
        "mainmenu",
        "b-tvseries-b",
        "widgetTarget",
        "videos"
    ],
    [
        "mainmenu",
        "b-tvseries-b",
        "widgetPath",
        "plugin://plugin.video.xprime/?action=tvshows&url=trakt_trending&reload=$INFO[Window(Home).Property(widgetreload-episodes)]"
    ],
    [
        "mainmenu",
        "b-tvseries-b",
        "widgetStyle",
        "Panel"
    ],
    [
        "mainmenu",
        "b-tvseries-b",
        "widgetLimit",
        "$NUMBER[100]"
    ],
    [
        "mainmenu",
        "b-tvseries-b",
        "widget.2",
        "Addon"
    ],
    [
        "mainmenu",
        "b-tvseries-b",
        "widgetName.2",
        "StreamLord - [B]TV Series[/B]"
    ],
    [
        "mainmenu",
        "b-tvseries-b",
        "widgetType.2",
        "videos"
    ],
    [
        "mainmenu",
        "b-tvseries-b",
        "widgetTarget.2",
        "videos"
    ],
    [
        "mainmenu",
        "b-tvseries-b",
        "widgetPath.2",
        "plugin://plugin.video.streamlord/?action=tvseries&reload=$INFO[Window(Home).Property(widgetreload)]$INFO[Window(Home).Property(widgetreload2)]"
    ],
    [
        "mainmenu",
        "b-tvseries-b",
        "widgetStyle.2",
        "Panel"
    ],
    [
        "mainmenu",
        "b-tvseries-b",
        "widgetLimit.2",
        "$NUMBER[100]"
    ],
    [
        "mainmenu",
        "b-tvseries-b",
        "icon",
        "DefaultShortcut.png"
    ],
    [
        "mainmenu",
        "b-tvseries-b",
        "thumb",
        "thumb"
    ],
    [
        "mainmenu",
        "trendingdaily",
        "widget",
        "Addon"
    ],
    [
        "mainmenu",
        "trendingdaily",
        "widgetName",
        "XPrime - Trending Daily"
    ],
    [
        "mainmenu",
        "trendingdaily",
        "widgetType",
        "videos"
    ],
    [
        "mainmenu",
        "trendingdaily",
        "widgetTarget",
        "videos"
    ],
    [
        "mainmenu",
        "trendingdaily",
        "widgetPath",
        "plugin://plugin.video.xprime/?action=tvshows&url=tmdb_trending_day&reload=$INFO[Window(Home).Property(widgetreload-episodes)]"
    ],
    [
        "mainmenu",
        "trendingdaily",
        "widgetStyle",
        "Panel"
    ],
    [
        "mainmenu",
        "trendingdaily",
        "widgetLimit",
        "$NUMBER[100]"
    ],
    [
        "mainmenu",
        "trendingdaily",
        "translatedPath",
        "ActivateWindow(Videos,\"plugin://plugin.video.xprime/?action=movies&url=tmdb_trending_day\",return)"
    ],
    [
        "mainmenu",
        "trendingdaily",
        "widget.2",
        "Addon"
    ],
    [
        "mainmenu",
        "trendingdaily",
        "widgetName.2",
        "XPrime - Trending Daily"
    ],
    [
        "mainmenu",
        "trendingdaily",
        "widgetType.2",
        "movies"
    ],
    [
        "mainmenu",
        "trendingdaily",
        "widgetTarget.2",
        "videos"
    ],
    [
        "mainmenu",
        "trendingdaily",
        "widgetPath.2",
        "plugin://plugin.video.xprime/?action=movies&url=tmdb_trending_day&reload=$INFO[Window(Home).Property(widgetreload-movies)]"
    ],
    [
        "mainmenu",
        "trendingdaily",
        "widgetStyle.2",
        "Panel"
    ],
    [
        "mainmenu",
        "trendingdaily",
        "widgetCase.2",
        "Glass"
    ],
    [
        "mainmenu",
        "trendingdaily",
        "widgetLimit.2",
        "$NUMBER[100]"
    ],
    [
        "mainmenu",
        "trendingdaily",
        "icon",
        "DefaultShortcut.png"
    ],
    [
        "mainmenu",
        "trendingdaily",
        "thumb",
        "image://DefaultMovies.png/"
    ],
    [
        "mainmenu",
        "b-searchalltorrents-b",
        "icon",
        "DefaultShortcut.png"
    ],
    [
        "mainmenu",
        "b-searchalltorrents-b",
        "thumb",
        "thumb"
    ],
    [
        "mainmenu",
        "plugin.audio.mp3streams",
        "translatedPath",
        "ActivateWindow(Music,\"plugin://plugin.audio.mp3streams\",return)"
    ],
    [
        "mainmenu",
        "plugin.audio.mp3streams",
        "widget",
        "Addon"
    ],
    [
        "mainmenu",
        "plugin.audio.mp3streams",
        "widgetName",
        "MP3 Streams - New Albums"
    ],
    [
        "mainmenu",
        "plugin.audio.mp3streams",
        "widgetType",
        "audio"
    ],
    [
        "mainmenu",
        "plugin.audio.mp3streams",
        "widgetTarget",
        "music"
    ],
    [
        "mainmenu",
        "plugin.audio.mp3streams",
        "widgetPath",
        "plugin://plugin.audio.mp3streams/?url=http%3A%2F%2Fmusicmp3.ru%2Fnew_albums.html%3Fpage%3D1&mode=15&name=New+Albums&iconimage=C%3A%5CUsers%5Cuser%5CAppData%5CRoaming%5CKodi%5Caddons%5Cplugin.audio.mp3streams%5Cart%2Fallnewalbums.jpg&list=new albums<>http://musicmp3.ru/new_albums.html?page=1<>C:\\Users\\user\\AppData\\Roaming\\Kodi\\addons\\plugin.audio.mp3streams\\art/allnewalbums.jpg&type=&reload=$INFO[Window(Home).Property(widgetreload-music)]"
    ],
    [
        "mainmenu",
        "plugin.audio.mp3streams",
        "widgetStyle",
        "List"
    ],
    [
        "mainmenu",
        "plugin.audio.mp3streams",
        "widgetCase",
        "Glass"
    ],
    [
        "mainmenu",
        "plugin.audio.mp3streams",
        "widgetLimit",
        "$NUMBER[100]"
    ],
    [
        "mainmenu",
        "plugin.audio.mp3streams",
        "widget.2",
        "Addon"
    ],
    [
        "mainmenu",
        "plugin.audio.mp3streams",
        "widgetName.2",
        "SoundCloud - [B]New & hot[/B]"
    ],
    [
        "mainmenu",
        "plugin.audio.mp3streams",
        "widgetType.2",
        "songs"
    ],
    [
        "mainmenu",
        "plugin.audio.mp3streams",
        "widgetTarget.2",
        "music"
    ],
    [
        "mainmenu",
        "plugin.audio.mp3streams",
        "widgetPath.2",
        "plugin://plugin.audio.soundcloud/charts/?action=trending&reload=$INFO[Window(Home).Property(widgetreload)]$INFO[Window(Home).Property(widgetreload2)]"
    ],
    [
        "mainmenu",
        "plugin.audio.mp3streams",
        "widgetStyle.2",
        "List"
    ],
    [
        "mainmenu",
        "plugin.audio.mp3streams",
        "widgetArt.2",
        "Square Poster"
    ],
    [
        "mainmenu",
        "plugin.audio.mp3streams",
        "widgetCase.2",
        "Glass"
    ],
    [
        "mainmenu",
        "plugin.audio.mp3streams",
        "widgetLimit.2",
        "$NUMBER[100]"
    ],
    [
        "mainmenu",
        "plugin.audio.mp3streams",
        "icon",
        "DefaultShortcut.png"
    ],
    [
        "mainmenu",
        "plugin.audio.mp3streams",
        "thumb",
        "thumb"
    ],
    [
        "mainmenu",
        "1037",
        "widget",
        "library"
    ],
    [
        "mainmenu",
        "1037",
        "widgetName",
        "1036"
    ],
    [
        "mainmenu",
        "1037",
        "widgetType",
        "favourite"
    ],
    [
        "mainmenu",
        "1037",
        "widgetTarget",
        ""
    ],
    [
        "mainmenu",
        "1037",
        "widgetPath",
        "favourites://"
    ],
    [
        "mainmenu",
        "1037",
        "widgetStyle",
        "Panel"
    ],
    [
        "mainmenu",
        "1037",
        "widgetLimit",
        "$NUMBER[100]"
    ],
    [
        "mainmenu",
        "1037",
        "icon",
        "special://skin/extras/icons/video-addons.png"
    ],
    [
        "mainmenu",
        "settings",
        "icon",
        "special://skin/extras/icons/settings.png"
    ],
    [
        "mainmenu",
        "33060",
        "icon",
        "special://skin/extras/icons/power.png"
    ]
]