[
    [
        "mainmenu",
        "b-movies-b",
        "translatedPath",
        "ActivateWindow(Videos,\"plugin://plugin.video.streamlord/?action=movies\",return)"
    ],
    [
        "mainmenu",
        "b-movies-b",
        "widget",
        "Addon"
    ],
    [
        "mainmenu",
        "b-movies-b",
        "widgetName",
        "StreamLord - [B]Movies[/B]"
    ],
    [
        "mainmenu",
        "b-movies-b",
        "widgetType",
        "videos"
    ],
    [
        "mainmenu",
        "b-movies-b",
        "widgetTarget",
        "videos"
    ],
    [
        "mainmenu",
        "b-movies-b",
        "widgetPath",
        "plugin://plugin.video.streamlord/?action=movies&reload=$INFO[Window(Home).Property(widgetreload-movies)]"
    ],
    [
        "mainmenu",
        "b-movies-b",
        "widgetRatio",
        "Fanart/Poster"
    ],
    [
        "mainmenu",
        "b-movies-b",
        "widgetLimit",
        "$NUMBER[100]"
    ],
    [
        "mainmenu",
        "b-movies-b",
        "icon",
        "DefaultShortcut.png"
    ],
    [
        "mainmenu",
        "b-movies-b",
        "thumb",
        "thumb"
    ],
    [
        "mainmenu",
        "b-tvseries-b",
        "translatedPath",
        "ActivateWindow(Videos,\"plugin://plugin.video.streamlord/?action=tvseries\",return)"
    ],
    [
        "mainmenu",
        "b-tvseries-b",
        "widget",
        "Addon"
    ],
    [
        "mainmenu",
        "b-tvseries-b",
        "widgetName",
        "StreamLord - [B]TV Series[/B]"
    ],
    [
        "mainmenu",
        "b-tvseries-b",
        "widgetType",
        "videos"
    ],
    [
        "mainmenu",
        "b-tvseries-b",
        "widgetTarget",
        "videos"
    ],
    [
        "mainmenu",
        "b-tvseries-b",
        "widgetPath",
        "plugin://plugin.video.streamlord/?action=tvseries&reload=$INFO[Window(Home).Property(widgetreload)]$INFO[Window(Home).Property(widgetreload2)]"
    ],
    [
        "mainmenu",
        "b-tvseries-b",
        "widgetRatio",
        "Fanart/Poster"
    ],
    [
        "mainmenu",
        "b-tvseries-b",
        "widgetLimit",
        "$NUMBER[100]"
    ],
    [
        "mainmenu",
        "b-tvseries-b",
        "icon",
        "DefaultShortcut.png"
    ],
    [
        "mainmenu",
        "b-tvseries-b",
        "thumb",
        "thumb"
    ],
    [
        "mainmenu",
        "b-topimdb-b",
        "translatedPath",
        "ActivateWindow(Videos,\"plugin://plugin.video.streamlord/?action=top_imdb\",return)"
    ],
    [
        "mainmenu",
        "b-topimdb-b",
        "widget",
        "Addon"
    ],
    [
        "mainmenu",
        "b-topimdb-b",
        "widgetName",
        "StreamLord - [B]Top IMDb[/B]"
    ],
    [
        "mainmenu",
        "b-topimdb-b",
        "widgetType",
        "videos"
    ],
    [
        "mainmenu",
        "b-topimdb-b",
        "widgetTarget",
        "videos"
    ],
    [
        "mainmenu",
        "b-topimdb-b",
        "widgetPath",
        "plugin://plugin.video.streamlord/?action=top_imdb&reload=$INFO[Window(Home).Property(widgetreload)]$INFO[Window(Home).Property(widgetreload2)]"
    ],
    [
        "mainmenu",
        "b-topimdb-b",
        "widgetRatio",
        "Fanart/Poster"
    ],
    [
        "mainmenu",
        "b-topimdb-b",
        "icon",
        "DefaultShortcut.png"
    ],
    [
        "mainmenu",
        "b-topimdb-b",
        "thumb",
        "thumb"
    ],
    [
        "mainmenu",
        "b-genres-b",
        "translatedPath",
        "ActivateWindow(Videos,\"plugin://plugin.video.streamlord/?action=genres\",return)"
    ],
    [
        "mainmenu",
        "b-genres-b",
        "widget",
        "Addon"
    ],
    [
        "mainmenu",
        "b-genres-b",
        "widgetName",
        "StreamLord - [B]Genres[/B]"
    ],
    [
        "mainmenu",
        "b-genres-b",
        "widgetType",
        "videos"
    ],
    [
        "mainmenu",
        "b-genres-b",
        "widgetTarget",
        "videos"
    ],
    [
        "mainmenu",
        "b-genres-b",
        "widgetPath",
        "plugin://plugin.video.streamlord/?action=genres&reload=$INFO[Window(Home).Property(widgetreload)]$INFO[Window(Home).Property(widgetreload2)]"
    ],
    [
        "mainmenu",
        "b-genres-b",
        "icon",
        "DefaultShortcut.png"
    ],
    [
        "mainmenu",
        "b-genres-b",
        "thumb",
        "thumb"
    ],
    [
        "mainmenu",
        "b-search-b",
        "translatedPath",
        "ActivateWindow(Videos,\"plugin://plugin.video.streamlord/?action=search\",return)"
    ],
    [
        "mainmenu",
        "b-search-b",
        "widget",
        "Addon"
    ],
    [
        "mainmenu",
        "b-search-b",
        "widgetName",
        "StreamLord - [B]Search[/B]"
    ],
    [
        "mainmenu",
        "b-search-b",
        "widgetType",
        "videos"
    ],
    [
        "mainmenu",
        "b-search-b",
        "widgetTarget",
        "videos"
    ],
    [
        "mainmenu",
        "b-search-b",
        "widgetPath",
        "plugin://plugin.video.streamlord/?action=search&reload=$INFO[Window(Home).Property(widgetreload)]$INFO[Window(Home).Property(widgetreload2)]"
    ],
    [
        "mainmenu",
        "b-search-b",
        "icon",
        "DefaultShortcut.png"
    ],
    [
        "mainmenu",
        "b-search-b",
        "thumb",
        "thumb"
    ],
    [
        "mainmenu",
        "24001",
        "icon",
        "DefaultAddon.png"
    ],
    [
        "mainmenu",
        "settings",
        "icon",
        "icons/big/Settings.png"
    ]
]